package com.naprock.hexudon.domain.model;

import com.naprock.hexudon.domain.model.Agent;
import com.naprock.hexudon.domain.valueobject.AgentType;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AgentTest {

    @Test
    void testAgentProperties() {
        Agent agent = new Agent();

        agent.setType(AgentType.PATROL);
        agent.setPosX(5);
        agent.setPosY(10);
        agent.setFuel(100);

        agent.setRemainingSteps(3);

        assertAll(
            () -> assertNotNull(agent.getId()),
            () -> assertTrue(agent.getId().matches("A\\d+"), "ID should match pattern A\\d+"),
            () -> assertEquals(AgentType.PATROL, agent.getType()),
            () -> assertEquals(5, agent.getPosX()),
            () -> assertEquals(10, agent.getPosY()),
            () -> assertEquals(100, agent.getFuel()),
            () -> assertEquals(3, agent.getRemainingSteps(), "remainingSteps should be 3"),
            () -> assertEquals(0, new Agent().getRemainingSteps(), "Default remainingSteps should be 0")
        );
    }

    @Test
    void testAgentConstructor() {
        Agent agent = new Agent(AgentType.REFUEL, 3, 4, 80);

        assertAll(
            () -> assertNotNull(agent.getId()),
            () -> assertTrue(agent.getId().matches("A\\d+"), "ID should match pattern A\\d+"),
            () -> assertEquals(AgentType.REFUEL, agent.getType()),
            () -> assertEquals(3, agent.getPosX()),
            () -> assertEquals(4, agent.getPosY()),
            () -> assertEquals(80, agent.getFuel())
        );
    }

    @Test
    void testAutoGeneratedId() {
        Agent agent1 = new Agent();
        Agent agent2 = new Agent();

        assertAll(
            () -> assertNotEquals(agent1.getId(), agent2.getId(), "IDs must be unique"),
            () -> assertTrue(agent1.getId().matches("A\\d+")),
            () -> assertTrue(agent2.getId().matches("A\\d+"))
        );
    }
}
